#!/usr/bin/env python3
"""Generates assets/js/documentation-data.js (SKU -> docs) from the single
source of truth in generate-product-pages.py, for the Documentation page's
searchable table. Run from anywhere: python3 scripts/generate-docs-data.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN_PATH = os.path.join(ROOT, "scripts", "generate-product-pages.py")
OUT_PATH = os.path.join(ROOT, "assets", "js", "documentation-data.js")

ns = {"__name__": "not_main", "__file__": GEN_PATH}
with open(GEN_PATH) as f:
    exec(compile(f.read(), GEN_PATH, "exec"), ns)
PRODUCTS = ns["PRODUCTS"]

data = {p["sku"]: p.get("docs") or [] for p in PRODUCTS}

with open(OUT_PATH, "w") as f:
    f.write("/* Generated by scripts/generate-docs-data.py - do not hand-edit. */\n")
    f.write("var VTRONIX_DOCS = " + json.dumps(data, indent=2) + ";\n")

print("wrote", OUT_PATH, "with", len(data), "products")
